import turtle

turtle.penup()
turtle.setpos(-100,-200)
turtle.pendown()
turtle.colormode(255)
turtle.bgcolor(245, 229, 86)

#base
turtle.begin_fill()
turtle.color('blue')
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()
turtle.color('black')


#teto
turtle.color('red')
turtle.begin_fill()
turtle.penup()
turtle.right(180)
turtle.forward(200)
turtle.pendown()
turtle.right(30)
turtle.forward(200)
turtle.right(120)
turtle.forward(200)
turtle.right(120)
turtle.forward(200)
turtle.end_fill()
turtle.color('black')

#janela
turtle.color('cyan')
turtle.begin_fill()
turtle.penup()
turtle.setpos(-70,-150)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()
turtle.color('black')


#porta
turtle.penup()
turtle.setpos(10, -200)
turtle.right(90)
turtle.pendown()
turtle.color('brown')
turtle.begin_fill()
turtle.forward(130)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(130)
turtle.right(90)
turtle.forward(60)
turtle.end_fill()
turtle.color('black')

#chamine
turtle.colormode(255)
turtle.color(56, 56, 55)
turtle.penup()
turtle.setpos(0,0)
turtle.right(180)
turtle.forward(70)
turtle.pendown()
turtle.begin_fill()
turtle.forward(30)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()
turtle.color('black')

#paisagem
turtle.penup()
turtle.setpos(0,0)
turtle.left(90)
turtle.forward(250)
turtle.left(90)
turtle.forward(175)
turtle.pendown()
turtle.pensize(10)
turtle.colormode(255)
turtle.pencolor(247, 93, 32)
turtle.circle(-50)
turtle.pensize(1)

turtle.right(90)
turtle.forward(4)
turtle.left(90)
turtle.colormode(255)
turtle.color(255, 59, 10)
turtle.begin_fill()
turtle.circle(-47)
turtle.end_fill()

turtle.hideturtle()

turtle.done()
